//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class TwitterSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TwitterSettings defaultInstance = ((TwitterSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TwitterSettings())));
        
        public static TwitterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TwitterAccounts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TwitterAccounts"]));
            }
            set {
                this["TwitterAccounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TwitterSearchTags {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TwitterSearchTags"]));
            }
            set {
                this["TwitterSearchTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TweetFormat {
            get {
                return ((string)(this["TweetFormat"]));
            }
            set {
                this["TweetFormat"] = value;
            }
        }
    }
}
