//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class NntpSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static NntpSettings defaultInstance = ((NntpSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NntpSettings())));
        
        public static NntpSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NntpServer {
            get {
                return ((string)(this["NntpServer"]));
            }
            set {
                this["NntpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NntpPort {
            get {
                return ((int)(this["NntpPort"]));
            }
            set {
                this["NntpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FilteredGroups {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilteredGroups"]));
            }
            set {
                this["FilteredGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FilteredWords {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilteredWords"]));
            }
            set {
                this["FilteredWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection NntpChannels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NntpChannels"]));
            }
            set {
                this["NntpChannels"] = value;
            }
        }
    }
}
